working_directory: &working_directory
  working_directory: ~/gazelle-server

docker_no_database: &docker_no_database
  docker:
    - image: thegazelle/gazelle-main-circleci-primary:0.0.6

docker_with_database: &docker_with_database
  docker:
    - image: thegazelle/gazelle-main-circleci-primary:0.0.6
    - image: circleci/mariadb:10.2
      environment:
        MYSQL_ROOT_PASSWORD: circleci_test_gazelle
        MYSQL_DATABASE: the_gazelle

defaults: &defaults
  <<: *working_directory
  <<: *docker_no_database

defaults_with_database: &defaults_with_database
  <<: *working_directory
  <<: *docker_with_database

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout

      # Complete setup
      - run: |
          sed 's/^DATABASE_PASSWORD=.*/DATABASE_PASSWORD=circleci_test_gazelle/' .sample-env |
          sed 's/^ROOT_DIRECTORY=.*/ROOT_DIRECTORY=\/home\/circleci\/gazelle-server/' |
          sed 's/^GAZELLE_ENV=.*/GAZELLE_ENV=CI/' > .env

      - persist_to_workspace:
          root: .
          paths:
            - .


  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Prep known hosts
          command: mkdir -p ~/.ssh && cp known_hosts ~/.ssh/known_hosts

      - run:
          name: Install dependencies in ci mode that is faster and ensures the lockfile is correct
          command: npm ci

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Make sure coverage folder exists
          command: mkdir -p coverage

      - run:
          name: Run unit tests
          command: timeout 1m npm run test:unit -- --ci

      - run:
          name: save coverage
          command: timeout 5m npm run test:unit -- --ci --coverage > coverage/unit

      - persist_to_workspace:
          root: .
          paths:
            - coverage/unit

  integration_test:
    <<: *defaults_with_database
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Make sure coverage folder exists
          command: mkdir -p coverage

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      # We rerun integration tests as they can some times be flaky.
      # TODO: When https://github.com/facebook/jest/issues/6470 is implemented we can use that instead
      - run:
          name: Run integration tests
          command: |
            function f {
              # We clear state in between in case after a failed run some databases are still there.
              # If we're good about database names etc. it shouldn't be a problem, but just in case
              # The script is taken from https://stackoverflow.com/questions/22301635/drop-all-databases-in-mysql#comment75681619_22301636
              mysql --protocol=TCP -uroot -pcircleci_test_gazelle -e "show databases" | egrep -v "Database|mysql|information_schema" | awk '{print "drop database " $1 ";select sleep(0.1);"}' | mysql --protocol=TCP -uroot -pcircleci_test_gazelle
              timeout 1m npm run test:it -- --ci
            }
            f || f || f


      - run:
          name: save coverage
          command: |
            function f {
              mysql --protocol=TCP -uroot -pcircleci_test_gazelle -e "show databases" | egrep -v "Database|mysql|information_schema" |gawk '{print "drop database " $1 ";select sleep(0.1);"}' | mysql --protocol=TCP -uroot -pcircleci_test_gazelle
              timeout 1m npm run test:it -- --ci --coverage > coverage/it
            }
            f || f || f

      - persist_to_workspace:
          root: .
          paths:
            - coverage/it

  send_coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: setup dependencies for code coverage
          command: sudo npm i -g coveralls

      - run:
          name: Send coverage to Coveralls
          command: cat coverage/* | coveralls

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Run ESLint
          command: npm run lint:js

      - run:
          name: Run Typescript to check types
          command: npm run lint:ts

      - run:
          name: Run our opinionated code formatter prettier
          command: npm run lint:prettier

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run: npm run build:production

      - persist_to_workspace:
          root: .
          paths:
            - 'build'
            - 'static/build'

  end_to_end_tests:
    <<: *defaults_with_database
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Run E2E tests
          command: ./.circleci/scripts/run-end-to-end-tests.sh

  prep_ssh:
    <<: *defaults
    steps:
      # Setup known_hosts so the VM allows ssh access without the prompt
      - run:
          name: Add server ssh keys to known_hosts
          command: mkdir -p ~/.ssh && ssh-keyscan -t rsa "$GAZELLE_SERVER_STAGING_IP" "$GAZELLE_SERVER_PRODUCTION_IP" >> ~/.ssh/known_hosts

      - run:
          name: Add Github RSA key to known_hosts
          command: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - persist_to_workspace:
          root: ~/.ssh
          paths:
            - known_hosts

  deploy_staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Prep known hosts
          command: mkdir -p ~/.ssh && cp known_hosts ~/.ssh/known_hosts

      - run:
          # We need this so that the build is correct as Webpack injects the environment variables in
          name: Get the environment file from the server
          command: scp "$GAZELLE_SERVER_STAGING_USER@$GAZELLE_SERVER_STAGING_IP":~/server/.env ./.env

      - run:
          name: Check environment file is up to date
          command: |
            node setup-env.js --check-outdated || (
              echo "The environment file on the server is outdated, you will have to manually update the environment file before you can rerun this deployment step" &&
              exit 1
            )

      - run:
          name: Rerun the build, but now with the correct environment
          command: npm run build:staging

      - run:
          name: Copy compiled javascript to the server
          command: |
            scp ./build/* "$GAZELLE_SERVER_STAGING_USER@$GAZELLE_SERVER_STAGING_IP":~/server/build/
            scp ./static/build/* "$GAZELLE_SERVER_STAGING_USER@$GAZELLE_SERVER_STAGING_IP":~/server/static/build/

      - run:
          name: Finalize deployment
          command: ssh "$GAZELLE_SERVER_STAGING_USER@$GAZELLE_SERVER_STAGING_IP" 'bash -ic "~/server/deployment-resources/scripts/finalize-deployment.sh"'

  deploy_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Prep known hosts
          command: mkdir -p ~/.ssh && cp known_hosts ~/.ssh/known_hosts

      - run:
          # We need this so that the build is correct as Webpack injects the environment variables in
          name: Get the environment file from the server
          command: scp "$GAZELLE_SERVER_PRODUCTION_USER@$GAZELLE_SERVER_PRODUCTION_IP":~/server/.env ./.env

      - run:
          name: Check environment file is up to date
          command: |
            node setup-env.js --check-outdated || (
              echo "The environment file on the server is outdated, you will have to manually update the environment file before you can rerun this deployment step" &&
              exit 1
            )

      - run:
          name: Rerun the build, but now with the correct environment
          command: npm run build:production

      - run:
          name: Copy compiled javascript to the server
          command: |
            scp ./build/* "$GAZELLE_SERVER_PRODUCTION_USER@$GAZELLE_SERVER_PRODUCTION_IP":~/server/build/
            scp ./static/build/* "$GAZELLE_SERVER_PRODUCTION_USER@$GAZELLE_SERVER_PRODUCTION_IP":~/server/static/build/

      - run:
          name: Finalize deployment
          command: ssh "$GAZELLE_SERVER_PRODUCTION_USER@$GAZELLE_SERVER_PRODUCTION_IP" 'bash -ic "~/server/deployment-resources/scripts/finalize-deployment.sh"'

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code

      - prep_ssh

      - install_dependencies:
          requires:
            - checkout_code
            - prep_ssh

      - unit_test:
          requires:
            - install_dependencies
      - integration_test:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies

      - send_coverage:
          requires:
            - unit_test
            - integration_test

      - end_to_end_tests:
          requires:
            - build

      # Deployment related
      - deploy_staging:
          requires:
            - send_coverage
            - lint
            - end_to_end_tests
            - prep_ssh
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - send_coverage
            - lint
            - end_to_end_tests
            - prep_ssh
          filters:
            branches:
              only: stable
